### ISSUE TITLE
Error that stops the forum

### ISSUE THREAD

**Issue by cwkhawand** [radixi0/flarum-ext-sharing#1]
( ! ) Notice: Undefined property: Illuminate\Database\Eloquent\Collection::$id in C:\wamp64\www\forums\vendor\radixi0\flarum-ext-sharing\src\Listener\AddOgTags.php on line 86
--

1 | 0.1457 | 236384 | {main}( ) | ...\index.php:0
2 | 2.2086 | 1110856 | Flarum\Http\AbstractServer->listen( ) | ...\index.php:16
3 | 3.1851 | 1803608 | Zend\Diactoros\Server->listen( ) | ...\AbstractServer.php:34
4 | 3.1851 | 1820344 | Flarum\Http\AbstractServer->__invoke( ) | ...\Server.php:166
5 | 20.4917 | 12062784 | Zend\Stratigility\MiddlewarePipe->__invoke( ) | ...\AbstractServer.php:53
6 | 20.8825 | 12273728 | Zend\Stratigility\Next->__invoke( ) | ...\MiddlewarePipe.php:75
7 | 20.8830 | 12279056 | Zend\Stratigility\Dispatch->__invoke( ) | ...\Next.php:113
8 | 20.8831 | 12279360 | Flarum\Http\Middleware\ParseJsonBody->__invoke( ) | ...\Dispatch.php:82
9 | 20.8831 | 12279552 | Zend\Stratigility\Next->__invoke( ) | ...\ParseJsonBody.php:30
10 | 20.8839 | 12283704 | Zend\Stratigility\Dispatch->__invoke( ) | ...\Next.php:113
11 | 20.8839 | 12284000 | Flarum\Http\Middleware\StartSession->__invoke( ) | ...\Dispatch.php:82
12 | 21.5420 | 12597488 | Zend\Stratigility\Next->__invoke( ) | ...\StartSession.php:33
13 | 21.5429 | 12601728 | Zend\Stratigility\Dispatch->__invoke( ) | ...\Next.php:113
14 | 21.5430 | 12602064 | Flarum\Http\Middleware\RememberFromCookie->__invoke( ) | ...\Dispatch.php:82
15 | 21.5430 | 12602192 | Zend\Stratigility\Next->__invoke( ) | ...\RememberFromCookie.php:38
16 | 21.5437 | 12606416 | Zend\Stratigility\Dispatch->__invoke( ) | ...\Next.php:113
17 | 21.5437 | 12606696 | Flarum\Http\Middleware\AuthenticateWithSession->__invoke( ) | ...\Dispatch.php:82
18 | 21.8301 | 13035480 | Zend\Stratigility\Next->__invoke( ) | ...\AuthenticateWithSession.php:33
19 | 21.8308 | 13039808 | Zend\Stratigility\Dispatch->__invoke( ) | ...\Next.php:113
20 | 21.8308 | 13040176 | Flarum\Http\Middleware\SetLocale->__invoke( )

**Comment by shaz13** [comment]
I was experiencing the same. Few users reported this error
